export { default as HomePage } from './HomePage';
export { default as PasswordRecoveryPage } from './PasswordRecoveryPage';
export { default as PasswordRecoveryConfirmPage } from './PasswordRecoveryConfirmPage';
export { default as LoginPage } from './LoginPage';
export { default as SignInPage } from './SignInPage';
export { default as ContactsPage } from './ContactsPage';
export { default as MyRecipesPage } from './MyRecipesPage';
export { default as MyRecipesFormPage } from './MyRecipesFormPage';
export { default as OtherUserPage } from './OtherUserPage';